version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/EnvEdu_Server
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 100
      runas: ubuntu




