version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/EnvEdu_Server

permissions:
  - object: /home/ubuntu/EnvEdu_Server
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: "0755"

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 100




